default_language_version:
    python: python3.8.13
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: no-commit-to-branch
    -   id: check-builtin-literals
    -   id: check-docstring-first
    -   id: debug-statements
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
    -   id: yapf
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: /home/chanho/anaconda3/envs/ai/bin/pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--rcfile=./.pylintrc", # Link to your config file
          "--load-plugins=pylint.extensions.docparams", # Load an extension
        ]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
    -   id: isort
-   repo: https://github.com/janosh/format-ipy-cells
    rev: v0.1.10
    hooks:
    -   id: format-ipy-cells
